name: searchable_internet_archive_videos
channels:
  - defaults
dependencies:
  - nvidia:cudnn
  - pip
  - pip:
     - ruamel.yaml
     - internetarchive
     - python-ffmpeg
     - pytest
     - faster-whisper
     - tabulate
     - more-itertools
